entry: /home/higuruchi/fuse-exp/data/hfs/development/config/entry.yaml
data: /home/higuruchi/fuse-exp/data/hfs/development/config/data.yaml
attr: /home/higuruchi/fuse-exp/data/hfs/development/config/attr.yaml
